name: Deployment
on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          GITHUB_TOKEN: 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
          BRANCH: gh-pages
          FOLDER: .
