name: Deployment
on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          GITHUB_TOKEN: ${{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}}
          BRANCH: gh-pages
          FOLDER: .
